
-- Создание таблицы проектов (приложений, которые мы отслеживаем)
create table public.projects (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  url text,
  api_key uuid default gen_random_uuid() not null, -- Ключ для отправки метрик с этого проекта
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) -- Привязка к пользователю Supabase (владельцу)
);

-- Включаем RLS (Row Level Security)
alter table public.projects enable row level security;

-- Политика: Пользователь видит только свои проекты
create policy "Users can view own projects"
  on public.projects for select
  using (auth.uid() = user_id);

create policy "Users can insert own projects"
  on public.projects for insert
  with check (auth.uid() = user_id);

-- Создание таблицы событий мониторинга (метрики, ошибки)
create table public.events (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) not null,
  type text not null, -- 'error', 'performance', 'visit'
  name text not null, -- 'page_view', 'api_call', 'runtime_error'
  status_code int, -- 200, 404, 500
  duration int, -- время выполнения в мс
  path text, -- URL путь где произошло событие
  message text, -- Текст ошибки или сообщение
  metadata jsonb, -- Любые доп. данные
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Индексы для ускорения выборок графиков
create index events_project_id_idx on public.events(project_id);
create index events_created_at_idx on public.events(created_at);
create index events_type_idx on public.events(type);

-- Включаем RLS
alter table public.events enable row level security;

-- Политика: Владелец проекта может читать события
create policy "Users can view events of own projects"
  on public.events for select
  using (
    exists (
      select 1 from public.projects
      where projects.id = events.project_id
      and projects.user_id = auth.uid()
    )
  );

-- Политика: Вставка событий разрешена публично по API KEY (или можно сделать secure function)
-- Для простоты пока разрешим авторизованным, но в идеале нужен Edge Function для инджеста.
-- Пока сделаем так: insert разрешен, если есть project_id (в реальном кейсе лучше через Service Role)
create policy "Enable insert for authenticated users only"
  on public.events for insert
  with check (true); 

-- Тестовые данные (ОПЦИОНАЛЬНО)
-- insert into public.projects (name, url, user_id) values ('My Website', 'https://example.com', auth.uid());
